Update Debug_PC_DirectX12.yml

diff --git a/.github/workflows/Debug_PC_DirectX12.yml b/.github/workflows/Debug_PC_DirectX12.yml
--- a/.github/workflows/Debug_PC_DirectX12.yml
+++ b/.github/workflows/Debug_PC_DirectX12.yml
@@ -7,13 +7,8 @@ on:
     branches: [ "master" ]
 
 env:
-  # Path to the solution file relative to the root of the project.
   SOLUTION_FILE_PATH: vgframework.sln
-
-  # Configuration type to build.
   BUILD_CONFIGURATION: Debug
-
-  # Platform to build.
   BUILD_PLATFORM: '"PC DirectX12"'
 
 permissions:
@@ -31,6 +26,10 @@ jobs:
       run: |
         # Locate MSBuild version 17.10.4+10fbfbf2e using vswhere
         $msbuildPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version "[17.10.4,17.10.5)" -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
+        if (-not $msbuildPath) {
+          Write-Error "MSBuild executable not found."
+          exit 1
+        }
         echo "MSBuild path: $msbuildPath"
         echo "::set-output name=msbuild::$msbuildPath"
         echo "$msbuildPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
@@ -42,4 +41,9 @@ jobs:
     - name: Build
       working-directory: ${{ env.GITHUB_WORKSPACE }}
       run: |
-        & "${{ steps.msbuild-path.outputs.msbuild }}" /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORM }} ${{ env.SOLUTION_FILE_PATH }}
+        $msbuild = "${{ steps.msbuild-path.outputs.msbuild }}"
+        if (-not $msbuild) {
+          Write-Error "MSBuild path not set correctly."
+          exit 1
+        }
+        & "$msbuild" /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORM }} ${{ env.SOLUTION_FILE_PATH }}
